
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boi-debit-card-service
  name: boi-debit-card-service
  namespace: prelogin-profile-dev
spec:
  selector:
    matchLabels:
      app: boi-debit-card-service
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: boi-debit-card-service
    spec:
      containers:
      - name: boi-debit-card-service
        image: pachaanilkumar/spring-boot-mongo-docker:b0997eb
        ports:
        - containerPort: 8080
      restartPolicy: Always
