
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bff-cms-service
  name: bff-cms-service
  namespace: investment=module
spec:
  selector:
    matchLabels:
      app: bff-cms-service
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: bff-cms-service
    spec:
      containers:
      - name: bff-cms-service
        image: your-docker-image
        ports:
        - containerPort: 8080
      restartPolicy: Always
