
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: boi-debit-card-service-gateway
  namespace: prelogin-profile-dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
