
apiVersion: v1
kind: Service
metadata:
  name: boi-debit-card-service
  namespace: prelogin-profile-dev
  labels:
    app: boi-debit-card-service
spec:
  selector:
    app: boi-debit-card-service
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
