
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: boi-debit-card-service-vs
  namespace: prelogin-profile-dev
spec:
  hosts:
  - "*"
  gateways:
  - boi-debit-card-service-gateway
  http:
  - match:
    - uri:
        prefix: /boi-debit-card-service
    route:
    - destination:
        host: boi-debit-card-service
        port:
          number: 8080
